// GENERATED by scripts/import-art.mjs — do not edit.
// Source of truth: design/art.manifest.json. Re-run `npm run art`.
import boot480 from './boot-480.webp';
import boot960 from './boot-960.webp';
import startHero480 from './start-hero-480.webp';
import startHero960 from './start-hero-960.webp';
import onboarding480 from './onboarding-480.webp';
import onboarding960 from './onboarding-960.webp';
import today480 from './today-480.webp';
import today960 from './today-960.webp';
import levelUp480 from './level-up-480.webp';
import levelUp960 from './level-up-960.webp';
import rank480 from './rank-480.webp';
import rank960 from './rank-960.webp';
import checkpoint480 from './checkpoint-480.webp';
import checkpoint960 from './checkpoint-960.webp';
import progress480 from './progress-480.webp';
import progress960 from './progress-960.webp';
import skills480 from './skills-480.webp';
import skills960 from './skills-960.webp';
import training480 from './training-480.webp';
import training960 from './training-960.webp';
import review480 from './review-480.webp';
import review960 from './review-960.webp';
import reviewWeekly480 from './review-weekly-480.webp';
import reviewWeekly960 from './review-weekly-960.webp';
import boss480 from './boss-480.webp';
import boss960 from './boss-960.webp';
import bossThrone480 from './boss-throne-480.webp';
import bossThrone960 from './boss-throne-960.webp';
import bossCleared480 from './boss-cleared-480.webp';
import bossCleared960 from './boss-cleared-960.webp';
import quote480 from './quote-480.webp';
import quote960 from './quote-960.webp';

export type ArtSlot =
  | 'boot'
  | 'start-hero'
  | 'onboarding'
  | 'today'
  | 'level-up'
  | 'rank'
  | 'checkpoint'
  | 'progress'
  | 'skills'
  | 'training'
  | 'review'
  | 'review-weekly'
  | 'boss'
  | 'boss-throne'
  | 'boss-cleared'
  | 'quote';

export type ArtMood = 'blue' | 'gold' | 'boss';

export interface ArtAsset {
  src: string;
  srcSet: string;
  /** 20px blurred placeholder, inlined — paints instantly, no request. */
  lqip: string;
  width: number;
  height: number;
  /** blue = effort, gold = evidence, boss = BOSS surfaces only. */
  mood: ArtMood;
  /** CSS object-position, keeping the figure clear of the copy. */
  focal: string;
  /** The plate carries its own tagline; do not overlay another. */
  hasText: boolean;
  /**
   * Default crop scale.
   *
   * Several plates carry their own lettering down a margin. A phone
   * viewport is narrower than the source aspect, so `cover` crops the
   * sides and slices that text mid-word — and half a word reads as a
   * rendering fault, which is worse than not showing it. The scale that
   * pushes it cleanly out of frame belongs to the plate, not to
   * whichever screen happens to use it first.
   */
  zoom: number;
}

/** null means the slot has no art yet — ArtLayer renders its procedural
 * gradient instead, and the screen still looks finished. */
export const ART: Record<ArtSlot, ArtAsset | null> = {
  'boot': {
    src: boot480,
    srcSet: `${boot480} 480w, ${boot960} 960w`,
    lqip: 'data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAADwBQCdASoUACQAPu1kqk8ppSOiMBVaqTAdiUAWI+HOUgAz14A7BLmzkhYTLKDXwJr3SmPBsVdmuAD+8qhGd+FKUlS0ukuJc/y8J27kdfA3QNvboxUdxfeTxGw7RsFU5ERd0u3VnW735BQxiOK9dcXoMVVsGC3uC1PFpbRfh0WNtFYbqgaQpy3r6HtmUh68AAA=',
    width: 940,
    height: 1672,
    mood: 'blue',
    focal: '50% 28%',
    hasText: false,
    zoom: 1,
  },
  'start-hero': {
    src: startHero480,
    srcSet: `${startHero480} 480w, ${startHero960} 960w`,
    lqip: 'data:image/webp;base64,UklGRrAAAABXRUJQVlA4IKQAAABQBgCdASoUACQAPu1yrlGppyQiqrgIATAdiWMAsswit0SDNIKCinAKsylbEVbIDx7rBrah82O9IqOdgAD+8PdDS843jodpT6vPZ59bu0/fJhjJjED/xgZcwzi8K632epL+Um7EzznpatYjpCe6Gs2PVnbUXc3hfQhbmB1x6a1fk84A8iD1T2tgGfanAnHMBxgTdE4BM+Uci8jgtU3GGNBTTNAAAA==',
    width: 941,
    height: 1672,
    mood: 'gold',
    focal: '50% 42%',
    hasText: true,
    zoom: 1.22,
  },
  'onboarding': {
    src: onboarding480,
    srcSet: `${onboarding480} 480w, ${onboarding960} 960w`,
    lqip: 'data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAACwBQCdASoUAB4APu1urlKppiQiqAgBMB2JbACdM1o0h+UB2KCKm7ogK8ZIvwxkCMSL6a0rTWAA/vKpE0JI/8F88zSyd2NwxsINhbtmx36oIqO4QPS7ytEwT4dVpBb0nf4+qHoM/Y+l5W6e5qoKfEz+q0XNRUSabN46DK38qRZ80K3Jyw4wAAAA',
    width: 1024,
    height: 1536,
    mood: 'blue',
    focal: '50% 30%',
    hasText: false,
    zoom: 1,
  },
  'today': {
    src: today480,
    srcSet: `${today480} 480w, ${today960} 960w`,
    lqip: 'data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAABwBQCdASoUABkAPu1srlKppaQiqAgBMB2JbACdMtpBqCOMf0TmSDKwlrOlRZn7i/3tSkyAAP7xC/SFauyu40wUIoJfIhhqjQas+DKKCR172mX1P3WVWhCvAHlSR0oRisanMQOW4LhxEhJUN+mzPID69jg7S4wpW7BSne4W0/S6/DFCD61Pe5gAAAA=',
    width: 1122,
    height: 1402,
    mood: 'blue',
    focal: '70% 25%',
    hasText: false,
    zoom: 1,
  },
  'level-up': {
    src: levelUp480,
    srcSet: `${levelUp480} 480w, ${levelUp960} 960w`,
    lqip: 'data:image/webp;base64,UklGRpAAAABXRUJQVlA4IIQAAACwBQCdASoUACQAPt1UpU2opKOiNVv8ARAbiWMAuwAhYc1IkpU/tSMIpu4eZCKG+km+V8V+oeAA/vQsxd0Phi/qWPKK6mIsbnzwnv3xu+fVG0UTdN3VoBu4lZS4gH/yKy9yAMruQNmNEnPrZf4SsfTP5VVNYCUQiHfjAmucZWeZodwAAAA=',
    width: 941,
    height: 1672,
    mood: 'blue',
    focal: '50% 45%',
    hasText: true,
    zoom: 1.6,
  },
  'rank': {
    src: rank480,
    srcSet: `${rank480} 480w, ${rank960} 960w`,
    lqip: 'data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAADQBQCdASoUACQAPu1eqU2ppSQiNVgIATAdiWUAxkAWCXefrOkO4IFkH90ikbcqoL7BYj5/sPQAAP7umOiz8XRiRQz5X3zdh6bu0H39iS/HUII+/JVMeyNXZeVassbGJ490HLzNFhlFvqWIQi73NOn9mlsOro6eQzdqYbB7EKaAAA==',
    width: 941,
    height: 1672,
    mood: 'gold',
    focal: '50% 40%',
    hasText: true,
    zoom: 1.5,
  },
  'checkpoint': {
    src: checkpoint480,
    srcSet: `${checkpoint480} 480w, ${checkpoint960} 960w`,
    lqip: 'data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAADwBQCdASoUACQAPu1qqk4ppqOiKrgN+TAdiUAW+yyYYx93G6W5fay8NBS1DORmeNkZnYVpf6xmDAD+9CzfPcei/DvoC/cH62WiBW8sAtX7BBaXzcfbVQE6jy+iZntMiiom1NlcUCPT3T7h4PKMi9ej19gMOIKYYR1WBRKt4aX39dCJTpovvKg/03pA3QhrRtmpOCMZwAA=',
    width: 941,
    height: 1672,
    mood: 'gold',
    focal: '50% 55%',
    hasText: false,
    zoom: 1,
  },
  'progress': {
    src: progress480,
    srcSet: `${progress480} 480w, ${progress960} 960w`,
    lqip: 'data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAABQBQCdASoUACQAPu1oqE6ppiOiMBVaqTAdiWIAtsgLPHYXb54GP3Sch9teG+J7V5svdIAA/vDLQiJOGqpcTa+PZ5EmAStke6v9wOGi9U5X0sHryXC8r2YtGyaMAw37iKNpLOTQMRKS49F/n5nRWOSIoPp8ApN23wGBhbZgDgAAAA==',
    width: 941,
    height: 1672,
    mood: 'blue',
    focal: '50% 35%',
    hasText: false,
    zoom: 1,
  },
  'skills': {
    src: skills480,
    srcSet: `${skills480} 480w, ${skills960} 960w`,
    lqip: 'data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAAAwBQCdASoUAB4APu1qr1CppaQiqAqpMB2JaACsMxx+ABLNI3FYaXW8K6DWtNrrEAbgAAD+8N96T8LbJo3l2d7N+aPQYTYhNvjs23F/G3/vaGPSX8hwMgojnXMkFLWvInx+0J7wqMgwdpnL6lNvzFTOEvDzjbZBVmnpbllcAAA=',
    width: 1024,
    height: 1536,
    mood: 'blue',
    focal: '50% 30%',
    hasText: false,
    zoom: 1,
  },
  'training': {
    src: training480,
    srcSet: `${training480} 480w, ${training960} 960w`,
    lqip: 'data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAACwBACdASoUACQAPu1kr1EppSQiqrgKATAdiWUAxgQQa0KVAJEbyQpZsY5NPCugAP7wCP0/JqSoQK7/AtQQf8InWWh2+g1zHRzEEz2WrYoIY5sLx6nIqRTnYUwAAA==',
    width: 941,
    height: 1672,
    mood: 'blue',
    focal: '50% 45%',
    hasText: true,
    zoom: 1.2,
  },
  'review': {
    src: review480,
    srcSet: `${review480} 480w, ${review960} 960w`,
    lqip: 'data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAADwBQCdASoUACQAPuVkp02pJiOiMBqtUSAciUAXyQLMvMKfrcVRMJHveUO83Yiski+AKdFMu7rmkAD+8qDatAZ2KhHykNcUge9jPds2UGFu/BHvqNxw/2G8ohZkjinQRusnzZkyIpH+kjso6mwMMbmLGhuWwVWI53dp4oO6YyubFHO9wUuCAAAA',
    width: 941,
    height: 1672,
    mood: 'blue',
    focal: '50% 35%',
    hasText: false,
    zoom: 1,
  },
  'review-weekly': {
    src: reviewWeekly480,
    srcSet: `${reviewWeekly480} 480w, ${reviewWeekly960} 960w`,
    lqip: 'data:image/webp;base64,UklGRpAAAABXRUJQVlA4IIQAAAAwBgCdASoUACQAPu1gqk2ppaQiMBVdUTAdiWUAx2wubM80H5tL/ZNflceiGCJ1rJd98aWH1YznsOsAAP73eH3N5s4Ex9f/bkILKxHkEgzFICgXu5Tr7Nus9D9UIDjulMoW2jjhtlu07aBWSlrc8coAMuAQVWi3sYCWNMgyRKe/6dH7gAA=',
    width: 941,
    height: 1672,
    mood: 'gold',
    focal: '50% 50%',
    hasText: true,
    zoom: 1.5,
  },
  'boss': {
    src: boss480,
    srcSet: `${boss480} 480w, ${boss960} 960w`,
    lqip: 'data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAAAwAwCdASoUAAgAPu1iqU2ppaOiMAgBMB2JZQAAela9O6aAAP7vyae2E1Q0uGej0+YUXXfNqfEzuMTWHUAAAA==',
    width: 1945,
    height: 808,
    mood: 'boss',
    focal: '50% 45%',
    hasText: true,
    zoom: 1,
  },
  'boss-throne': {
    src: bossThrone480,
    srcSet: `${bossThrone480} 480w, ${bossThrone960} 960w`,
    lqip: 'data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAABQBgCdASoUACQAPuFioE2opiMiNVgMARAcCUAUu+1/lQYSVT1GNG0TPv52FvZ5JDuhy+LdtRUfdiqs0AD+9CjtseBBbjQou/FOKzqHEOEFHqnuT1k0zmH+KBDC+PsYmxSLZwdFJRBOdotci7W5tc0C5KN4sV9ytCquZt6Wi1SaVToAP2DqgAAA',
    width: 941,
    height: 1672,
    mood: 'boss',
    focal: '50% 40%',
    hasText: false,
    zoom: 1,
  },
  'boss-cleared': {
    src: bossCleared480,
    srcSet: `${bossCleared480} 480w, ${bossCleared960} 960w`,
    lqip: 'data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAABQBQCdASoUAB4APu1opU2ppiMiMBgMATAdiWUApawPR9uK/K9P3EjanUopaPTxr1+j3NAA/vFtGtpfgYm4zkyBmVVl57rdy/1s3utOsQlRS/clDyFDcW/rmclG3eM1OpyxcYlKbrQ2ni7VoGUUPx4AAAA=',
    width: 1024,
    height: 1536,
    mood: 'gold',
    focal: '50% 45%',
    hasText: true,
    zoom: 1.45,
  },
  'quote': {
    src: quote480,
    srcSet: `${quote480} 480w, ${quote960} 960w`,
    lqip: 'data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAAAwBgCdASoUACQAPulepU2pJSOiMBqtUSAdCWMAt+uKAi+jJgJtVX7Ow6kG6p3QPGBVMDH2aV0jnlIAAP7wyXCOfg3owEIgUBf+/n7Sa+bw5xg4L++H6CF2ar6mCr6DChmlLvrs1Hz5Duo92TZ2XdSkFhF82cuMs38HrIJPLJ8r8QPodUgtwcYAAAA=',
    width: 941,
    height: 1672,
    mood: 'blue',
    focal: '50% 45%',
    hasText: true,
    zoom: 1,
  },
};
